In [1]:
import pandas as pd

C:\Users\uchoudhary\AppData\Local\Temp\ipykernel_12932\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [15]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep='\t')
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### 1. How many products cost more than $10.00?

In [4]:
chipo.item_price.info()

<class 'pandas.core.series.Series'>
RangeIndex: 4622 entries, 0 to 4621
Series name: item_price
Non-Null Count  Dtype
--------------  -----
4622 non-null   object
dtypes: object(1)
memory usage: 36.2+ KB

In [16]:
# step_1
chipo.item_price = chipo.item_price.replace({r'\$':""},regex=True).astype(float)
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [19]:
# step_2 : delete the duplicates in item_name and quantity
chipo_cleaned = chipo.drop_duplicates(['item_name'])

#step_3 : chipo_filtered
chipo_one_product = chipo_cleaned[chipo_cleaned.quantity == 1]

chipo_procusts_list = chipo.query('item_price > 10')
chipo_procusts_list.head

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
33,17,1,Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99
34,17,1,Bottled Water,NaN,$1.09
38,18,1,Chips and Tomatillo Green Chili Salsa,NaN,$2.95
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75
40,19,1,Chips,NaN,$2.15
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75
54,25,1,Steak Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.99
56,26,1,Barbacoa Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$9.25
57,26,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
62,28,1,Veggie Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
92,40,1,Steak Crispy Tacos,"[Fresh Tomato Salsa, Sour Cream]",$9.25
111,49,1,Chips and Tomatillo Red Chili Salsa,NaN,$2.95
168,75,1,Barbacoa Crispy Tacos,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.75
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
191,85,1,Chips and Roasted Chili-Corn Salsa,NaN,$2.39
233,102,1,Chips and Roasted Chili Corn Salsa,NaN,$2.95
237,103,1,Carnitas Soft Tacos,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$9.25
250,109,1,Chicken Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$10.98
263,114,1,Canned Soft Drink,[Coke],$1.25
298,129,1,6 Pack Soft Drink,[Sprite],$6.49
300,130,1,Chips and Tomatillo-Red Chili Salsa,NaN,$2.39
510,214,1,Burrito,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",$7.40
520,217,1,Crispy Tacos,[Adobo-Marinated and Grilled Steak],$7.40
554,230,1,Carnitas Crispy Tacos,[Roasted Chili Corn Salsa],$9.25
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99
674,279,1,Chips and Mild Fresh Tomato Salsa,NaN,$3.00
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
1132,468,1,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.89
1229,501,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",$11.89
1414,575,1,Salad,"[Brown Rice, Adobo-Marinated and Grilled Chick...",$7.40
1653,668,1,Veggie Crispy Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49
1694,686,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.49
3750,1500,1,Carnitas Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99